Removed rsync dependecy. Switched to SCP.

diff --git a/.local/bin/dotfiles b/.local/bin/dotfiles
--- a/.local/bin/dotfiles
+++ b/.local/bin/dotfiles
@@ -30,7 +30,7 @@ case "$OS" in
 	;;
 esac
 
-read -n 1 -s -p "Press any key to get started..."
+read -r -n 1 -s -p "Press any key to get started..."
 echo ""
 
 # Install nix in user-mode.
@@ -54,13 +54,13 @@ else
 fi
 
 # Preparation: Get ssh keys
-if ! command -v rsync &>/dev/null; then
-	echo "rsync could not be found. Please install rsync and then retry."
+if ! command -v scp &>/dev/null; then
+	echo "scp could not be found. Please install scp and then retry."
 	exit
 fi
 echo -e "${GREEN}Getting SSH keys...${NC}"
-# Download SSH keys from a local-only machine with rsync
-rsync -avh dietpi@10.134.6.112:/mnt/dietpi_userdata/secrets/id_ed25519* $HOME/.ssh/
+# Download SSH keys from a local-only machine with scp 
+scp dietpi@10.134.6.112:/mnt/dietpi_userdata/secrets/id_ed25519* $HOME/.ssh/
 
 # Download dotfiles repo
 function config {
