Getting SSH keys via rsync.

diff --git a/.local/bin/dotfiles b/.local/bin/dotfiles
--- a/.local/bin/dotfiles
+++ b/.local/bin/dotfiles
@@ -6,6 +6,7 @@ YELLOW='\033[1;33m'
 NC='\033[0m' # No Color
 NIX_ROOT="/nix"
 
+# Install nix in user-mode.
 echo -e "${GREEN}Installing Nix...${NC}"
 if [ -d "$NIX_ROOT" ]; then
 	echo -e "${YELLOW}Nix is already installed. Skipping...${NC}"
@@ -14,8 +15,8 @@ else
 	. $HOME/.nix-profile/etc/profile.d/nix.sh
 fi
 
+# Install home-manager.
 echo -e "${GREEN}Installing Home-Manager...${NC}"
-
 if home-manager --version >/dev/null 2>&1; then
 	echo -e "${YELLOW}Home-Manager is already installed. Skipping...${NC}"
 else
@@ -26,12 +27,13 @@ else
 fi
 
 # Preparation: Get ssh keys
+if ! command -v rsync &>/dev/null; then
+	echo "rsync could not be found. Please install rsync and then retry."
+	exit
+fi
 echo -e "${GREEN}Getting SSH keys...${NC}"
-echo -e "${ORANGE}Please connect your Yubikey and press any key to continue${NC}"
-read ans
-pushd $HOME/.ssh
-ssh-keygen -K
-popd
+# Download SSH keys from a local-only machine with rsync
+rsync -avh dietpi@10.134.6.112:/mnt/dietpi_userdata/secrets/id_ed25519* $HOME/.ssh/
 
 # Download dotfiles repo
 function config {
